SET NAMES 'utf8';
CREATE DATABASE IF NOT EXISTS `base_database` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `base_database`;

CREATE TABLE client(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ip CHAR(64) NOT NULL,
	visits INT UNSIGNED NOT NULL,
	banned INT DEFAULT 0 NOT NULL
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE activity(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	client BIGINT UNSIGNED NOT NULL,
	details_en TEXT NOT NULL,
	details_fr TEXT NOT NULL,
	_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE activity ADD CONSTRAINT activity_constraint FOREIGN KEY (client) REFERENCES client(id);
