SET NAMES 'utf8';
DROP DATABASE IF EXISTS `phpx_PHPX`;
CREATE DATABASE IF NOT EXISTS `phpx_PHPX` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `phpx_PHPX`;

CREATE TABLE IF NOT EXISTS phpx(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	maintenance INT UNSIGNED NOT NULL
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO phpx(maintenance) VALUES (0);
