SET NAMES 'utf8';
DROP DATABASE IF EXISTS `phpx_PHPX`;
CREATE DATABASE IF NOT EXISTS `phpx_PHPX` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `phpx_PHPX`;

/*Holds some website info*/
CREATE TABLE IF NOT EXISTS phpx(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	maintenance INT UNSIGNED NOT NULL
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

/*Default maintenance mode to off (0)*/
INSERT INTO phpx(maintenance) VALUES (0);

/*Clients infos*/
CREATE TABLE IF NOT EXISTS client(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ip CHAR(64) NOT NULL,
	visits INT UNSIGNED NOT NULL,
	banned INT DEFAULT 0,
	name TEXT,
	password TEXT,
	email TEXT,
	level INT UNSIGNED DEFAULT 0,
	restrict_ip INT UNSIGNED DEFAULT 0
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

/*Logs*/
CREATE TABLE IF NOT EXISTS activity (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	client BIGINT UNSIGNED NOT NULL,
	details TEXT NOT NULL,
	_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	level INT UNSIGNED DEFAULT 0

) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

/*Link each activity to a client account*/
ALTER TABLE activity ADD CONSTRAINT activity_constraint FOREIGN KEY (client) REFERENCES client(id);



